export interface InspectionArea {
  id: string;
  name: string;
  icon: string;
  description: string;
  checklist: string[];
}

export const INSPECTION_AREAS: InspectionArea[] = [
  {
    id: "exterior",
    name: "Exterior",
    icon: "🏠",
    description: "Roof, siding, foundation, grading, gutters, windows, doors",
    checklist: [
      "Roof condition (shingles, flashing, penetrations)",
      "Gutters and downspouts",
      "Siding and trim condition",
      "Foundation visible cracks or damage",
      "Grading and drainage",
      "Exterior doors and windows",
      "Driveways and walkways",
      "Decks, porches, patios",
      "Exterior electrical (outlets, fixtures)",
      "Landscaping issues affecting structure",
    ],
  },
  {
    id: "garage",
    name: "Garage",
    icon: "🚗",
    description: "Garage door, floor, walls, electrical, fire separation",
    checklist: [
      "Garage door operation and auto-reverse",
      "Floor condition and slope",
      "Walls and ceiling condition",
      "Fire separation (wall between garage and house)",
      "Electrical outlets and wiring",
      "Vehicle door weatherstripping",
    ],
  },
  {
    id: "kitchen",
    name: "Kitchen",
    icon: "🍳",
    description: "Appliances, counters, plumbing, electrical, ventilation",
    checklist: [
      "Countertops and cabinets",
      "Sink and faucet operation",
      "Under-sink plumbing and disposal",
      "Dishwasher operation",
      "Range/oven/cooktop",
      "Range hood ventilation",
      "Refrigerator (if included)",
      "GFCI outlets near water sources",
      "Floor condition",
      "Signs of water damage",
    ],
  },
  {
    id: "bathrooms",
    name: "Bathrooms",
    icon: "🚿",
    description: "Fixtures, plumbing, ventilation, tile, water damage",
    checklist: [
      "Toilet operation and mounting",
      "Sink and faucet operation",
      "Tub/shower condition",
      "Tile and grout condition",
      "Caulking around fixtures",
      "Exhaust fan operation",
      "GFCI outlets",
      "Water pressure and drainage",
      "Signs of water damage or mold",
      "Under-sink plumbing",
    ],
  },
  {
    id: "bedrooms",
    name: "Bedrooms",
    icon: "🛏️",
    description: "Windows, outlets, closets, ceiling, walls, floors",
    checklist: [
      "Windows operation and condition",
      "Electrical outlets (code requires minimum)",
      "Ceiling and wall condition",
      "Floor condition",
      "Closet condition",
      "Smoke detector presence",
      "Egress window (basement bedrooms)",
    ],
  },
  {
    id: "living-areas",
    name: "Living Areas",
    icon: "🛋️",
    description: "Living room, dining room, hallways, stairs",
    checklist: [
      "Wall and ceiling condition",
      "Floor condition",
      "Windows and doors",
      "Stairway condition and handrails",
      "Fireplace and chimney (if applicable)",
      "Electrical outlets and switches",
      "Smoke/CO detectors",
    ],
  },
  {
    id: "attic",
    name: "Attic",
    icon: "🏚️",
    description: "Insulation, ventilation, structure, roof underside",
    checklist: [
      "Insulation type and depth",
      "Ventilation (soffit, ridge, gable)",
      "Roof sheathing condition",
      "Rafters/trusses condition",
      "Signs of moisture or leaks",
      "Electrical wiring condition",
      "Bathroom venting (should go to exterior)",
      "Signs of pest activity",
    ],
  },
  {
    id: "basement",
    name: "Basement / Crawlspace",
    icon: "🪜",
    description: "Foundation, moisture, structure, sump pump",
    checklist: [
      "Foundation walls condition",
      "Signs of water intrusion",
      "Floor condition",
      "Structural supports (columns, beams)",
      "Sump pump operation",
      "Moisture barriers (crawlspace)",
      "Insulation",
      "Signs of pest activity",
    ],
  },
  {
    id: "electrical",
    name: "Electrical System",
    icon: "⚡",
    description: "Panel, wiring, outlets, grounding, GFCI/AFCI",
    checklist: [
      "Service panel condition and capacity",
      "Circuit breakers properly labeled",
      "Wiring type (copper, aluminum, knob-and-tube)",
      "GFCI protection (kitchen, bath, garage, exterior)",
      "AFCI protection (bedrooms)",
      "Grounding and bonding",
      "Visible wiring condition",
      "Double-tapped breakers",
    ],
  },
  {
    id: "plumbing",
    name: "Plumbing System",
    icon: "🔧",
    description: "Supply lines, drains, water heater, fixtures",
    checklist: [
      "Main water shutoff location and operation",
      "Supply line material and condition",
      "Drain line condition",
      "Water heater age and condition",
      "Water heater temperature setting",
      "Expansion tank (if applicable)",
      "Water pressure",
      "Signs of leaks",
    ],
  },
  {
    id: "hvac",
    name: "HVAC System",
    icon: "🌡️",
    description: "Heating, cooling, ductwork, thermostat, filters",
    checklist: [
      "Furnace/heat pump age and condition",
      "AC condenser age and condition",
      "Thermostat operation",
      "Ductwork condition",
      "Air filter condition",
      "Flue/venting (gas furnace)",
      "Refrigerant lines condition",
      "Carbon monoxide detection",
    ],
  },
];

export const DEFAULT_INSPECTION_ORDER = INSPECTION_AREAS.map(a => a.id);
